### ISSUE TITLE
v0.0.3 broke ResNet creation

### ISSUE THREAD

**Issue by BouncyKonju** [raphaelreme/torch-resnet#1]
#### Description

In release v0.0.3 on Python 3.11, creating _any_ ResNet model throws a TypeError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/--/.conda/envs/--/lib/python3.11/site-packages/torch_resnet/resnet.py", line 205, in __init__
    self._make_layer(
  File "/home/--/.conda/envs/--/lib/python3.11/site-packages/torch_resnet/resnet.py", line 228, in _make_layer
    layers.append(block(self.out_planes, planes, shortcut, stride_, width, drop_rate))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BasicBlock.__init__() takes 3 positional arguments but 7 were given
```

This is not limited to BasicBlock (Bottleneck shows the same behaviour) and using one of the classes defined in `__all__` does not fix it either. 

#### To Reproduce

Install torch_resnet v0.0.3 using pip, run Python3.11.

```
import torch_resnet

model = torch_resnet.ResNet50()
```

Throws the error.

**Comment by raphaelreme** [comment]
Thanks for the report, I'm able to reproduce the bug.. It should be easy to fix, probably a silly mistake in the last version!

**Comment by raphaelreme** [comment]
I deployed v0.0.4 which should fix the issue! Let me know if this is not the case

**Comment by BouncyKonju** [comment]
Yes, that fixed it. Thanks a lot
